### ISSUE TITLE
BT Serial to Arduino

### ISSUE THREAD

**Issue by alexp3d** [diegomtzg/ScreenBacklight#4]
One thing that would be worth while is to have the arduino communicate via wirelessly with the host computer with a blue tooth module. This would eliminate the need to plug in to a com port. Then, only a single plug would be required to power the arduino/LEDs

**Comment by diegomtzg** [comment]
Honestly that would be pretty sick.. let's do it

**Comment by alexp3d** [comment]
I have a BT serial module we can use. 

Additionally, we should consider having a dedicated Arduino unit and Arduino sketch to run the code to do the BT/computer/LED stuff. So we would have two Arduino units, one that demos the actual LED/computer screen stuff via BT and another that has the other modes for demo purposes.
